mavenproject1/src/main/java/cz/mendelu/pp/engine/FileUploadBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.mendelu.pp.engine;

import cz.mendelu.pp.database.FileManager;
import cz.mendelu.pp.models.FileRecord;
import cz.mendelu.pp.models.User;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.servlet.ServletContext;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;
import org.apache.commons.io.FilenameUtils;
import org.apache.commons.io.IOUtils;
import org.primefaces.event.FileUploadEvent;
import org.primefaces.model.UploadedFile;

/**
 *
 * @author User_Petan
 */
@ManagedBean
@ViewScoped
public class FileUploadBean {

    private FileManager myFileManager = new FileManager();
    private UploadedFile file = null;

    private List<String> selectedCategories = new ArrayList<>();

    private Integer uploadDays = 5;

    private final String filesFolder = "C:\\data";

    public UploadedFile getFile() {
        return file;
    }

    public Integer getUploadDays() {
        return uploadDays;
    }

    public void setUploadDays(Integer uploadDays) {
        this.uploadDays = uploadDays;
    }

    public void setFile(UploadedFile file) {
        this.file = file;
    }

    public List<String> getSelectedCategories() {
        return selectedCategories;
    }

    public void setSelectedCategories(List<String> selectedCategories) {
        this.selectedCategories = selectedCategories;
    }

    public String getUploadStatus() {
        if (file == null) {
            return  "Vyberte prosím soubor.";
        } else {
            return file.getFileName() + " - nahrán na server.";
        }
    }

    public void upload() {
        if (file.getFileName().length() > 1) {
            FacesMessage message = new FacesMessage("Succesful", file.getFileName() + " is uploaded.");
            FacesContext.getCurrentInstance().addMessage(null, message);
        } else {
            FacesMessage message = new FacesMessage("Upload error.");
            FacesContext.getCurrentInstance().addMessage(null, message);
        }

    }

    public void upload2(FileUploadEvent event) {

    }

    public void confirm() throws Exception {

        // jestliže byl nahrán soubor
        if (file != null && file.getFileName().length() >= 1) {
            
            FacesMessage message = new FacesMessage("Ano, zapsani souboru, zavolani db a redirect");
            FacesContext.getCurrentInstance().addMessage(null, message);

            // Fyzické vytvoření souboru
            String filename = FilenameUtils.getName(file.getFileName());
            InputStream input = file.getInputstream();

            OutputStream output = new FileOutputStream(new File(filesFolder, filename));
            IOUtils.copy(input, output);
            String filePath = filesFolder + "\\" + filename;
            // Vytvoreni FileRecordu
            createFileRecord(filePath);
            output.close();
            input.close();
            
            System.out.println("jjo nahrani bylo dobre");

        } else {
            if(file == null)System.out.println("file je null");
            // jestliže nebyl nahranej žadnej soubor
            FacesMessage message = new FacesMessage("Nebyl nahrán žádný soubor!");
            FacesContext.getCurrentInstance().addMessage(null, message);
        }
    }

    public void createFileRecord(String filePath) {
        HttpSession session = (HttpSession) FacesContext.getCurrentInstance().getExternalContext().getSession(false);
        User u = (User) session.getAttribute("user");
        File f = new File(filePath);
        LocalDate now = LocalDate.now();

        String sizeString = String.format("%.2f", (double) f.length() / 1000000);

        // vytvoreni objektu zaznamu souboru
        FileRecord newFileRecord = new FileRecord(
                f.getName(),
                u.getId_user(),
                FilenameUtils.getExtension(filePath.toLowerCase()),
                sizeString,
                Date.from(now.atStartOfDay().atZone(ZoneId.systemDefault()).toInstant()),
                Date.from(now.plusDays(uploadDays).atStartOfDay().atZone(ZoneId.systemDefault()).toInstant()),
                filePath
        );

        // jestliže byly vybrany nějaké kategorie
        if (!selectedCategories.isEmpty()) {
            newFileRecord.setCategories(selectedCategories);
        }

        try {
            // fyzicke vloženi do db
            myFileManager.insert(newFileRecord);

            // redirect
            FacesContext context = FacesContext.getCurrentInstance();
            HttpServletRequest origRequest = (HttpServletRequest) context.getExternalContext().getRequest();
            String contextPath = origRequest.getContextPath();
            try {
                FacesContext.getCurrentInstance().getExternalContext().redirect("index.xhtml");
            } catch (IOException e) {
                e.printStackTrace();
            }

        } catch (ParseException ex) {
            FacesMessage message = new FacesMessage("Problém při nahrávání do NOSQL databáze");
            FacesContext.getCurrentInstance().addMessage(null, message);
        }

    }

}

mavenproject1/src/main/java/cz/mendelu/pp/engine/MainBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.mendelu.pp.engine;

import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.JsonNode;
import com.mashape.unirest.http.Unirest;
import com.mashape.unirest.http.exceptions.UnirestException;
import cz.mendelu.pp.database.FileManager;
import cz.mendelu.pp.database.RelationalDatabase;
import cz.mendelu.pp.models.FileRecord;
import cz.mendelu.pp.models.User;
import java.awt.event.ActionEvent;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.Serializable;
import java.sql.SQLException;
import java.text.ParseException;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.imageio.ImageIO;
import javax.servlet.ServletOutputStream;
import javax.servlet.http.Cookie;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import jdk.nashorn.internal.objects.annotations.Property;
import org.apache.commons.io.FilenameUtils;
import org.bson.Document;

/**
 *
 * @author User_Petan
 */
@ManagedBean(name = "mainbean")
@ViewScoped
public class MainBean implements Serializable {

    private FileManager myFileManager = new FileManager();
    private String selectedExtension = "all";
    private String selectedCategory = "all";
    private Map<String, Integer> options = new HashMap<>();
    private String newCategory = null;
    private List<String> newCategories = new ArrayList();

    @PostConstruct
    public void init() {
        FacesContext context = FacesContext.getCurrentInstance();
        ResourceBundle bundle = context.getApplication().getResourceBundle(context, "msg");
        String q1 = bundle.getString("question1");
        String q2 = bundle.getString("question2");
        String q3 = bundle.getString("question3");
        String q4 = bundle.getString("question4");
        
        options.put(q1, 1);
        options.put(q2, 2);
        options.put(q3, 3);
        options.put(q4, 4);
        
    }
    
    
    public Map<String, Integer> getOptions() {
        return options;
    }

    public void setOptions(Map<String, Integer> options) {
        this.options = options;
    }



    public String getSelectedCategory() {
        return selectedCategory;
    }

    public void setSelectedCategory(String selectedCategory) {
        this.selectedCategory = selectedCategory;
    }

    public String getNewCategory() {
        return newCategory;
    }

    public void setNewCategory(String newCategory) {
        this.newCategory = newCategory;
    }

    public String getSelectedExtension() {
        return selectedExtension;
    }

    public void addToNewCategories() {
        newCategories.add(newCategory);
        System.out.println("nova kategorie" + newCategory);
        System.out.println("vypis novych pocet: " + newCategories.size());
    }

    public void setSelectedExtension(String selectedExtension) {
        this.selectedExtension = selectedExtension;
    }

    // Vrátí všechny přípony ,které se nacházejí u uživatelových souborů
    public List<String> getExtensions() throws ParseException {
        HttpSession session = (HttpSession) FacesContext.getCurrentInstance().getExternalContext().getSession(false);
        User u = (User) session.getAttribute("user");

        Map<String, String> filters = new HashMap();
        filters.put("username", u.getId_user());
        List<String> resultExtensions = new ArrayList();

        for (FileRecord fr : myFileManager.find(filters)) {
            if (!resultExtensions.contains(fr.extension)) {
                resultExtensions.add(fr.extension);
            }
        }
        return resultExtensions;
    }

    // Vrátí všechny přípony ,které se nacházejí u uživatelových souborů
    public List<String> getAllCategories() throws ParseException {
        Map<String, String> filters = new HashMap();
        List<String> resultCategories = new ArrayList();

        for (FileRecord fr : myFileManager.find(filters)) {
            if (fr.getCategories() != null) {
                List<String> fr_categories = fr.getCategories();
                for (String fr_category : fr_categories) {
                    if (!resultCategories.contains(fr_category)) {
                        resultCategories.add(fr_category);
                    }
                }
            }
        }

        if (newCategories.size() > 0) {
            for (String newCategory : newCategories) {
                if (!resultCategories.contains(newCategory) && newCategory.length() > 0) {
                    resultCategories.add(newCategory);
                }
            }
        }

        return resultCategories;
    }

    // Vrátí všechny přípony ,které se nacházejí u uživatelových souborů
    public List<String> getMyCategories() throws ParseException {
        HttpSession session = (HttpSession) FacesContext.getCurrentInstance().getExternalContext().getSession(false);
        User u = (User) session.getAttribute("user");

        Map<String, String> filters = new HashMap();
        filters.put("username", u.getId_user().toString());
        List<String> resultCategories = new ArrayList();

        for (FileRecord fr : myFileManager.find(filters)) {
            if (fr.getCategories() != null) {
                List<String> fr_categories = fr.getCategories();
                for (String fr_category : fr_categories) {
                    if (!resultCategories.contains(fr_category)) {
                        resultCategories.add(fr_category);
                    }
                }
            }
        }

        return resultCategories;
    }

    // vrátí seznam všech souborů ,které uživatel vlastní
    public List<FileRecord> getMyBrief() throws ParseException {
        HttpSession session = (HttpSession) FacesContext.getCurrentInstance().getExternalContext().getSession(false);
        User u = (User) session.getAttribute("user");

        Map<String, String> filters = new HashMap();
        filters.put("username", u.getId_user().toString());

        if (!selectedExtension.trim().equalsIgnoreCase("all")) {
            filters.put("extension", selectedExtension);
        }

        if (!selectedCategory.trim().equalsIgnoreCase("all")) {
            filters.put("categories", selectedCategory);
        }

        return myFileManager.find(filters);
    }

    public void callFileDelete(Integer id, String fileUrl) {

        // nejprve vymazu vyzicky soubor
        File file = new File(fileUrl);

        if (file.delete()) {
            System.out.println(file.getName() + " is deleted!");
        } else {
            System.out.println("Delete operation is failed.");
        }

        // nasledne vymazu zaznam z mongoDB
        myFileManager.delete(id);

        // TODO
        // tady by to bylo úžasný nějak vypsat hlášku o provedeným vymazáním
    }

    public String getUserName() {
        HttpSession session = (HttpSession) FacesContext.getCurrentInstance().getExternalContext().getSession(false);
        User u = (User) session.getAttribute("user");
        return u.getName();
    }

    public String getUserId() {
        HttpSession session = (HttpSession) FacesContext.getCurrentInstance().getExternalContext().getSession(false);
        User u = (User) session.getAttribute("user");
        return u.getId_user().toString();
    }

    public String getUserEmail() {
        HttpSession session = (HttpSession) FacesContext.getCurrentInstance().getExternalContext().getSession(false);
        User u = (User) session.getAttribute("user");
        return u.getEmail();
    }

    public Boolean isRemoteLogged() {
        HttpSession session = (HttpSession) FacesContext.getCurrentInstance().getExternalContext().getSession(false);
        User u = (User) session.getAttribute("user");

        if (u.getLoginType().equals("relationalDb")) {
            return false;
        } else {
            return true;
        }
    }

    public String getUserProfilePicture() throws UnirestException, ClassNotFoundException, SQLException, IOException {
        HttpSession session = (HttpSession) FacesContext.getCurrentInstance().getExternalContext().getSession(false);
        User u = (User) session.getAttribute("user");

        // defaultne tam bude jen panacek..
        String image_url = "http://d22r54gnmuhwmk.cloudfront.net/app-assets/global/default_user_icon-7a95ec473c1c41f6d020d32c0504a0ef.jpg";

        // jen pokud je typ loginu vzdálené tak se bude tahat profilovka od nekud
        if (u.getLoginType().equals("facebook")) {
            HttpResponse<String> response = Unirest.get("http://graph.facebook.com/" + u.getId_user() + "/picture?type=large&redirect=false").asString();
            JsonParser parser = new JsonParser();
            JsonObject o = parser.parse(response.getBody()).getAsJsonObject();
            image_url = o.get("data").getAsJsonObject().get("url").getAsString();
        }

        if (u.getLoginType().equals("google")) {

mavenproject1/src/main/webapp/secured/file-new.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core">
    <h:head>
        <h:outputStylesheet name="css/style.css" />
        <h:outputScript library="js" name="common.js" />
        <script type="text/javascript" src="https://code.jquery.com/jquery-2.2.0.js"></script>


        <!-- tohle tady mam jen abych se toho otravnyho okynka zbavil, protoze mi prekriva vysouvaci menu-->
        <style type="text/css">
            .ui-growl{
                left:20px;
            }
        </style>
    </h:head>
    <h:body style="background: white;">

        <div id="login-top">
            <div id="welcome-label"><h2><h:outputText value="#{msg.welcome} "/> <h:outputText value="#{mainbean.userName}"/>! </h2></div>
            <div class="dropdown" onclick="toggleDropDown();">
                <img src="#{mainbean.userProfilePicture}" class="profile-picture"/>
                <b class="caret"/>
                <!-- TODO když se to menu zobrazí ,tak to rozšíří stránku, to menu prostě leze do prava do boku - to je škaredá -->
                <div id="myDropdown" class="dropdown-content">
                    <h:form>
                        <a href="#{request.contextPath}/secured/index.xhtml">Home</a>
                        <a href="#about">About</a>
                        <a href="#contact">Contact</a>
                        <h:commandLink id="Link1" value="Logout" action="#{mainbean.logout()}" />
                    </h:form>
                </div>
            </div>
        </div>
        <div id="login-bottom">
            
            
            Stránka s formulářem pro vytvoření souboru

            <div id="new-file-form" style="height: 100%; background-color: #E9E9E9; border-radius: 50px; padding: 90px;">
                <!-- tohle je k informacnim zpravam o uploadu, je to kdesi v rohu a mozna by to chtelo i nastylovat.. -->
                <p:growl id="messages" showDetail="true" />


                <!-- file upload, hnus chce to s tim neco udelat -->
                <h:outputText value="#{fileUploadBean.uploadStatus}" />
                <h:form enctype="multipart/form-data">
                    <p>Vyberte soubor</p>
                    <p:fileUpload value="#{fileUploadBean.file}" mode="simple" skinSimple="true"/>
                    <p:commandButton value="Nahrát soubor na server" ajax="false" actionListener="#{fileUploadBean.upload}" />

                </h:form>




                <h:form>
                    <h4>Vyberte kategorie souboru</h4>
                    <p:selectManyCheckbox id="basic" value="#{fileUploadBean.selectedCategories}">
                        <!-- TODO kategorie by to chtelo vypisovat z db a taky moznost pridavat dalsi, prace pro Peťana -->
                        <f:selectItems value="#{mainbean.allCategories}" var="category" itemLabel="#{category}" itemValue="#{category}" />
                    </p:selectManyCheckbox>

                    <h4>Nová kategorie</h4>
                    <p:inputText value="#{mainbean.newCategory}" placeholder="Zadejte název nové kategorii" />
                    <p:commandButton value="Přidat novou katerogii" ajax="false" actionListener="#{mainbean.addToNewCategories()}" />

                    <h4>Vyberte délku upladu (ve dnech)</h4>
                    <h:outputLabel for="days" value="Basic Spinner: " />
                    <p:spinner id="days" value="#{fileUploadBean.uploadDays}" min="5" max="60"/>


                    <br></br>
                    <hr></hr>

                    <p:commandButton value="Vytvořit novou položku" ajax="false" actionListener="#{fileUploadBean.confirm}" />
                </h:form>

            </div>



        </div>
    </h:body>
</html>

mavenproject1/src/main/webapp/secured/index.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:c="http://java.sun.com/jsp/jstl/core">
    <h:head>
        <h:outputStylesheet name="css/style.css" />
        <h:outputScript library="js" name="common.js" />
        <h:outputScript library="primefaces" name="jquery/jquery.js" target="head" />
    </h:head>
    <h:body style="background: white;">

        <p:toolbar style="background-color: #c74534" >
            <f:facet name="left">
                <div id="welcome-label"><h2><h:outputText value="#{msg.welcome} #{mainbean.userName}!" /></h2></div>
            </f:facet>

            <f:facet name="right">
                <div class="dropdown" onclick="toggleDropDown();">
                    <c:choose>
                        <c:when test="#{mainbean.isRemoteLogged() == true}">
                            <img src="#{mainbean.userProfilePicture}" class="profile-picture"/>
                        </c:when>
                        <c:when test="#{mainbean.isRemoteLogged() == false}">

                            <c:choose>
                                <c:when test="#{mainbean.userProfilePicture.length() > 0}">
                                    <img src="data:image/png;base64,#{mainbean.userProfilePicture}" class="profile-picture"/>
                                </c:when>
                                <c:when test="#{mainbean.userProfilePicture.length() == 0}">
                                    <img src="http://d22r54gnmuhwmk.cloudfront.net/app-assets/global/default_user_icon-7a95ec473c1c41f6d020d32c0504a0ef.jpg" class="profile-picture"/>
                                </c:when>
                            </c:choose>

                        </c:when>
                    </c:choose>
                    <b class="caret"/>

                </div>
                <ul class="main-navigation" id='nav' style="position:absolute;">
                    <li><a href="#">#{msg.home}</a></li>
                    <li><a href="#">#{msg.settings}</a> <ul>
                            <li><a href="#">#{msg.language}</a>
                                <ul>
                                    <h:form>
                                        <li><h:commandLink actionListener="#{languageSwitcher.changeLanguage('en')}" id="en">#{msg.english}</h:commandLink></li>
                                        <li><h:commandLink actionListener="#{languageSwitcher.changeLanguage('de')}" id="de">#{msg.german}</h:commandLink></li>
                                        <li><h:commandLink actionListener="#{languageSwitcher.changeLanguage('cd')}" id="cs">#{msg.czech}</h:commandLink></li>
                                    </h:form>
                                </ul>

                            </li>
                            <li><h:form><p:commandLink value="#{msg.color}" type="button" onclick="PF('pickUpColor').show();"  >#{msg.color}</p:commandLink></h:form></li>
                        </ul>
                    </li>
                    <li><h:form><h:commandLink actionListener="#{mainbean.logout()}" >#{msg.logout}</h:commandLink></h:form></li>

                </ul>
            </f:facet>
        </p:toolbar>
        <p:dialog header="#{msg.color_picker}" widgetVar="pickUpColor" minHeight="200">
            <p:colorPicker mode="inline" value="#{colorView.colorInline}"/>
            <p:commandButton value="Submit" actionListener="#{colorView}" style="margin-left: 20px" />
        </p:dialog>
        <div id="login-bottom">
            <h:form enctype="multipart/form-data" style="background-color: #c74534;" styleClass="upload-files">
                <h1>#{msg.new_file}</h1>
                <p:fieldset legend="#{msg.choose_file}" style="margin-bottom:20px;margin-top:10px;">
                    <h:panelGrid columns="2" cellpadding="5">
                        <h:outputText value="#{fileUploadBean.uploadStatus}"/>
                        <p:fileUpload value="#{fileUploadBean.file}" mode="simple" skinSimple="true" label="#{msg.choose_file}"  />
                    </h:panelGrid>
                </p:fieldset>

                <p:fieldset legend="#{msg.choose_category}" style="margin-bottom:20px">
                    <h:panelGrid columns="4" cellpadding="5">
                        <h:outputText value="#{msg.choose_panel}."/>
                        <h:panelGrid columns="2" cellpadding="10">
                            <p:selectCheckboxMenu id="category_menu" value="#{fileUploadBean.selectedCategories}" label="#{msg.category_file}"
                                                  filter="true" filterMatchMode="startsWith" panelStyle="width:300px" style="width:200px;">
                                <f:selectItems value="#{mainbean.allCategories}" />
                            </p:selectCheckboxMenu>
                        </h:panelGrid>
                        <p:inputText value="#{mainbean.newCategory}" placeholder="#{msg.new_category_placeholder}" style="min-width: 300px;"/>
                        <p:commandButton value="#{msg.new_category_btt}" update="category_menu" actionListener="#{mainbean.addToNewCategories()}"/>
                    </h:panelGrid>
                </p:fieldset>
                <p:fieldset legend="#{msg.set_duration}" style="margin-bottom:20px">
                    <h:panelGrid columns="2" cellpadding="5">
                        <h:outputLabel for="days" value="#{msg.upload_duration} " />
                        <p:spinner id="days" value="#{fileUploadBean.uploadDays}" min="5" max="60"/>
                    </h:panelGrid>
                </p:fieldset>
                <h:commandButton actionListener="#{fileUploadBean.confirm()}" value="#{msg.upload_file}" styleClass="ui-button-main" style="margin-left: 1640px;float:none;padding: 15px 30px !important;font-size:20px;"/>

            </h:form>

            <p:growl id="messages" showDetail="true" />


            <table width="100%">
                <tr>
                    <td>
                        <p>#{msg.filter_extension}</p>
                        <h:form>
                            <p:selectOneButton value="#{mainbean.selectedExtension}">
                                <f:selectItems value="#{mainbean.extensions}" var="extension" itemLabel="#{extension}" itemValue="#{extension}" />
                                <f:selectItem itemLabel="#{msg.all_files}" itemValue="all" />
                                <!-- <f:ajax render="fileList"/>!-->
                            </p:selectOneButton>
                        </h:form>
                    </td>
                    <td>
                        <p>#{msg.filter_category}</p>
                        <h:form>
                            <p:selectOneButton value="#{mainbean.selectedCategory}">
                                <f:selectItems value="#{mainbean.myCategories}" var="category" itemLabel="#{category}" itemValue="#{category}" />
                                <f:selectItem itemLabel="#{msg.all_files}" itemValue="all" />
                                <!--  <f:ajax render="fileList"/>!-->
                            </p:selectOneButton>
                        </h:form>
                    </td>
                </tr>
            </table>



            <h:panelGrid styleClass="no-items" rendered="#{empty mainbean.myBrief}">
                <h:graphicImage value="/resources/images/no-items.png"  styleClass="no-items"/>
                <h1>#{msg.no_files}</h1>
            </h:panelGrid>

            <h:panelGroup  rendered="#{not empty mainbean.myBrief}">
                <p:dataTable id="fileList" var="fileRecord" value="#{mainbean.myBrief}" style="text-align: center;">
                    <p:column headerText="#{msg.name_file}" sortBy="#{fileRecord.filename}">
                        <h:outputText value="#{fileRecord.filename}" />
                    </p:column>

                    <p:column headerText="#{msg.category_file}">
                        <ui:repeat var="categoryString" value="#{fileRecord.categories}">
                            <span><h:outputText value="#{categoryString}" />, </span>
                            <!--doplnit podminku !-->
                        </ui:repeat>
                    </p:column>

                    <p:column headerText="#{msg.dateOfCreated_file}" sortBy="#{fileRecord.created_date}">
                        <h:outputText value="#{fileRecord.created_date}">
                            <f:convertDateTime pattern="dd/MM/yyyy"></f:convertDateTime>  
                        </h:outputText>

                    </p:column>

                    <p:column headerText="#{msg.dateOfExpiration_file}">
                        <h:outputText value="#{fileRecord.expiration_date}">
                            <f:convertDateTime pattern="dd/MM/yyyy"></f:convertDateTime> 
                        </h:outputText>
                    </p:column>
                    <p:column headerText="#{msg.type_file}">
                        <h:outputText value="#{fileRecord.extension}" />
                    </p:column>

                    <p:column headerText="#{msg.size_file}">
                        <h:outputText value="#{fileRecord.size} MB" />
                    </p:column>

                    <p:column headerText="#{msg.link_file}">
                        <h:form style="text-align: center;">
                            <h:commandLink action="#{mainbean.downloadFile(fileRecord.file_url, fileRecord.filename)}">
                                <h:graphicImage name="images/download.png" style="width:30px;height:30px;" />
                            </h:commandLink>
                        </h:form>
                    </p:column>

                    <p:column headerText="#{msg.delete}">
                        <h:form style="text-align: center;">
                            <h:commandLink action="#{mainbean.callFileDelete(fileRecord.id,fileRecord.file_url)}" type="Delete" onclick="return confirm('#{msg.delete_dialog}')">
                                <h:graphicImage name="images/delete.png" style="width:30px;height:30px;" />
                            </h:commandLink>
                        </h:form>
                    </p:column>

                    <f:facet name="footer">

                    </f:facet>
                </p:dataTable>
            </h:panelGroup>


        </div>
    </h:body>
</html>